---
- name: 'restart bind'
  service: 'name={{ bind_service_name }} state=restarted'

- name: remove journal file
  file: "path=/etc/bind/db.{{ bind_top_level_domain }}.jnl state=absent"

- name: remove rev journal file
  file: "path=/etc/bind/db.{{ bind_top_level_domain }}_rev.jnl state=absent"
